// 统一出入口
export * from './ThemeManager'

export * from './PermissionManager'

export * from './CleanerManager'

export * from './UserCalendarManager'

export * from './UserAuthManager'

export * from './AudioCapturerManager'

export * from './AVPlayerManager'

export * from './BackgroundRunningManager'

export * from './LocationManager'

// import { permissionManager } from './PermissionManager'
// export { permissionManager }